### ISSUE TITLE
Access Gazebo installed on a mac host

### ISSUE THREAD

**Issue by cthorey** [osrf/docker_images#55] opened 2017-05-31 15:51 UTC
Hi,
First, thanks for the great work of maintaining these images.
I tried to reproduce the example in the [deployment example](https://hub.docker.com/_/gazebo/).
Everything is working properly except when I tried to connect the gzclient (on my mac machine) to the container. 

I just got 
```
[Msg] Waiting for master.
```

I guess this is due to the fact that **Per-container IP addressing is not possible** on docker-for-mac. I tried to Port forwarding instead mapping 11345:11345 and then setting up GAZEBO_MASTER_URI=0.0.0.0:11345.

This appears to launch gazebo on my mac but then gazebo got stuck on the **preparing your world** screen. 

Can you think of any workaround ? 
Thanks

PS :  I am running mac osx sierra with gazebo version 8.1.0 install on my mac. The container is also running gazebo version 8.1.0.

**Comment by scpeters** [comment] 2017-05-31 19:14
For debugging the networking setup, it might be easier to use the `gz` command, like `gz stats` or `gz topic -l`. What is the IP address of the docker container that you are using?

**Comment by cthorey** [comment] 2017-05-31 19:24
Thx for the quick answer,
it's 172.17.0.2. 
The output of $(docker inspect --format '{{ .NetworkSettings.IPAddress }}' gazebo).

**Comment by cthorey** [comment] 2017-05-31 19:32
If this is of any help, when forwarding the port and connecting from GAZEBO_MASTER_URI=0.0.0.0:11345, gazebo froze on preparing your world.

The output of gz stats is
```
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >: boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Abort trap: 6
```
and gz topic -l 

```
gz topic -l
/gazebo/default/atmosphere
/gazebo/default/diagnostics
/gazebo/default/factory
/gazebo/default/factory/light
/gazebo/default/gui
/gazebo/default/joint
/gazebo/default/light
/gazebo/default/light/modify
/gazebo/default/log/control
/gazebo/default/log/status
/gazebo/default/model/info
/gazebo/default/model/modify
/gazebo/default/physics
/gazebo/default/physics/contacts
/gazebo/default/playback_control
/gazebo/default/pose/info
/gazebo/default/pose/local/info
/gazebo/default/pose/modify
/gazebo/default/request
/gazebo/default/response
/gazebo/default/undo_redo
/gazebo/default/user_cmd
/gazebo/default/user_cmd_stats
/gazebo/default/visual
/gazebo/default/wind
/gazebo/default/world_control
/gazebo/default/world_stats
/gazebo/server/control
/gazebo/world/modify
```

**Comment by ruffsl** [comment] 2017-05-31 19:58
Perhaps the trouble stems from the way Docker for Mac uses a VM to host a linux kernel for the docker engine, and the oddities in passing through network traffic through the host->VM->container network interfaces. I have no Mac to test this, but there seem to be a lot of discussion on this topic:
https://forums.docker.com/t/access-host-not-vm-from-inside-container/11747

If you happen to need just one one containerized gzserver, have you tried using the --net=host run arg? This will bind the container to all interfaces available to the VM (I assume the network bridge interface it uses), circumventing any docker networking. Perhaps this would help to isolate the issue in VM network setup vs the docker network behind it.

**Comment by cthorey** [comment] 2017-05-31 21:21
Yes, I indeed think this is where the problem comes from. Thx for the tip but, unfortunately, even using --net=host results in gzclient hanging on **waiting for master**.

**Comment by ruffsl** [comment] 2017-06-06 02:22
Is the VM's network configured; i.e. are you able to use netcat to test socket connections from mac host to guest VM?
Also for intra docker engine networking, can a `gz` command in one container connect to a `gzserver` container, with both containers on the same docker engine/ virtual docker network?

**Comment by piotrmilos** [comment] 2017-07-30 09:41
@cthorey Did you manage to solve the problem. I think I have exactly the same one :)

**Comment by cthorey** [comment] 2017-07-30 17:09
@piotrmilos Unfortunately no, I switched back to a linux machine where everything works as expected.

**Comment by ruffsl** [comment] 2017-08-03 17:53
Looks like this is a mac issue, not specific to these docker images. Closing for now, but feel free to comment if more debug info surfaces.

**Closed by ruffsl** 2017-08-03 17:53 UTC

**Comment by pickledgator** [comment] 2017-09-06 20:06
It appears that gazebo is using random TCP ports for its transport layer, and since Mac docker requires you to forward each of the ports individually to map them to the host, this complicates things. We're able to get the gzclient to communicate with the gzserver (running inside the docker), however, it hangs at loading the world. We can reproduce the error by running "gz stats" on the mac host -- which also hangs. This is a minimal application which simply opens a transport subscriber to ~/world/stats. Is there any way to force gzserver to only use certain ports (or a range of ports) in it's random port mapping?

**Comment by j-rivero** [comment] 2017-09-06 21:55
I assume that you are using gazebo8, aren't you? Probably @caguero could help us with your question.

**Comment by pickledgator** [comment] 2017-09-06 22:00
I am actually using gazebo7, but we have also tried gazebo8 and saw the same problem.

**Comment by scpeters** [comment] 2017-09-06 22:33
does mac docker support host networking?

**Comment by himty** [comment] 2020-01-09 21:22
Old thread, but I got Gazebo in Docker to work by running both gzserver and gzclient in the Docker then using x11vnc and xvfb to get the display back to my computer, following dershow's hint for his workaround from here https://github.com/osrf/docker_images/issues/167#issuecomment-401454144

```
docker pull gazebo:latest
docker run -p 5900:5900 -d -v="/tmp/.gazebo/:/root/.gazebo/" --name=gazebo gazebo

docker exec -it gazebo bash  # get into the Docker

apt-get update
apt-get install x11vnc -y
apt update
apt install xvfb ufw -y
Xvfb :1 -screen 0 1600x1200x16 &
export DISPLAY=:1.0
gzclient &
x11vnc -display  
```

Then I opened a VNC viewer like "VNC Viewer for Google Chrome"
Address = localhost:5900

voila

**Comment by stevenlee090** [comment] 2020-01-22 23:57
@himty thanks for the instructions! I was able to get mine working by following the same steps.

**Comment by Interaze** [comment] 2020-07-31 00:25
Not to beat a dead horse, but revisiting after a year or two and it seems like ```network_mode: host``` does make a difference currently within docker-compose for mac and windows. I remember building a project with selenium and python where the configuration was the solution a few months ago and when I specify my docker-compose version at 3.7, it appears to change the IP. I've been hammering away at this today to see if there are any permutations that could work, but I'm curious if anyone would be able to help carry the torch.

When I run it, it changes my publicized address to 192.168.65.3. Compared to prior where it would state it as 127.0.0.2(I believe). With that in mind, I'm currently incapable or connecting at this point, but it is progress! I know that XQuartz can be especially slow for Catalina so hopefully we can roll this further.

Current Code:
```
version: '3.7'

services:
    simulation:
        build:
          dockerfile: Dockerfile.dev
          context: ./Simulation
        volumes:
          - /tmp/.gazebo/:/tmp/.gazebo/
        network_mode: host
```

Reference Source:
https://forums.docker.com/t/option-network-mode-host-in-docker-compose-file-not-working-as-expected/51682

Just to make this ping several of the interested party:
@pickledgator 
@cthorey 
@j-rivero 
@ruffsl 
@scpeters

**Comment by mkusold** [comment] 2020-09-29 19:42
> Old thread, but I got Gazebo in Docker to work by running both gzserver and gzclient in the Docker then using x11vnc and xvfb to get the display back to my computer, following dershow's hint for his workaround from here [#167 (comment)](https://github.com/osrf/docker_images/issues/167#issuecomment-401454144)
> 
> ```
> docker pull gazebo:latest
> docker run -p 5900:5900 -d -v="/tmp/.gazebo/:/root/.gazebo/" --name=gazebo gazebo
> 
> docker exec -it gazebo bash  # get into the Docker
> 
> apt-get update
> apt-get install x11vnc -y
> apt update
> apt install xvfb ufw -y
> Xvfb :1 -screen 0 1600x1200x16 &
> export DISPLAY=:1.0
> gzclient &
> x11vnc -display  
> ```
> 
> Then I opened a VNC viewer like "VNC Viewer for Google Chrome"
> Address = localhost:5900
> 
> voila

I'm having troubles following along. When I run the last line, I get:
```
root@d664dff42868:/# x11vnc -display 
not enough arguments for: -display
```

Do you know what I'm missing with the display argument?
