### ISSUE TITLE
Frequency of tag rebuilds for `osrf/ros2`?

### ISSUE THREAD

**Issue by aprotyas** [osrf/docker_images#563] opened 2021-08-24 09:57 UTC
Hi, I noticed that the [`devel`](https://hub.docker.com/layers/osrf/ros2/devel/images/sha256-8578d811a068f3d803a05ca4a26f9bf5c4c8d72df32697bbbf8b2fd72dbf730c?context=explore) tag on Dockerhub has not been pushed in about a month now. I was just curious to know if there's a schedule to push?

**Comment by sloretz** [comment] 2021-09-03 16:58
Thanks for the report! This is a duplicate of this issue: osrf/docker_images#112

In short they get updated when the Ubuntu base image updates. There's no button we can click on dockerhub to clear the cache and rebuild them, and it's not as simple as adding a line in the Dockerfile to break the cache because the change needs to be accepted by the upstream Docker Library maintainers.

**Comment by ruffsl** [comment] 2021-09-07 15:06
The devel tag is an image under the osrf org, not the upstream official library. I suspect docker hubs change in making auto builds a subscription feature has interrupted our nightly build triggers. I was told that osrf had applied for open source plan on docker hub to retain this functionality, but perhaps this isn't yet in effect. I'll look into it this afternoon

**Comment by ruffsl** [comment] 2021-09-07 23:00
>  I was told that osrf had applied for open source plan on docker hub to retain this functionality, but perhaps this isn't yet in effect. I'll look into it this afternoon

Yep, looks like the osrf org no longer has access to auto rebuilds, thus the current stale images.

![image](https://user-images.githubusercontent.com/2293573/132420827-c06b73fb-1d1c-495c-88b1-0582320022ba.png)

CC @nuclearsandwich @tfoote

**Comment by tfoote** [comment] 2021-09-20 08:58
We still haven't heard back about our application to the Docker Open Source Program. They promised an answer to our application within 2 weeks on July 16th but I haven't heard anything back.  I just pinged them back.

**Comment by tfoote** [comment] 2021-09-27 22:06
There was a promise of a few days response to my last email. However I still haven't heard anything. And now that it's been over a month I think that we should start thinking about other options.

**Comment by aprotyas** [comment] 2021-10-13 05:49
Any updates? These images were very useful for me!

**Comment by tfoote** [comment] 2021-10-30 00:17
After one month more and no word back from Docker Open Source Project I think we should not expect any more action on that front. I think the latest thing that I read was that there were 40 projects approved which means that they've only approved a very small set of open source projects and they all appear to be very closely related to docker itself.

**Comment by ruffsl** [comment] 2021-11-02 14:45
Just to add to that update, we are now planning to migrate to GitHub actions to host the docker image build pipeline, like we did over on the Nav2 repo, but instead keeping Docker Hub as the image registry.

**Comment by tfoote** [comment] 2021-11-15 18:29
Hey great news. I was just informed that OSRF has been accepted into the Docker Open Source Program. 

"We have allow-listed your namespace "osrf" and this should come into effect in the next week or so. With this allowed-listing, the Docker data pull rate policies that went into effect last November, will not apply to the users pulling images from your namespace.  "

**Comment by ruffsl** [comment] 2021-11-17 22:52
@tfoote , great to hear that OSRF has been accepted into the Docker Open Source Program! However, I'm afraid this allowed-listing to exempt us from the Docker data pull rate policies did not re-enable our automated build service on DockerHub, as the admin panel still looks the same as from https://github.com/osrf/docker_images/issues/563#issuecomment-914680111 . From my prior email offline, did you have the chance to create and provision a DockerHub machine account, for our GitHub actions to use to push built images?

**Comment by gavanderhoorn** [comment] 2022-01-17 19:02
Has auto-building of the images been sorted in the meantime?

**Comment by tfoote** [comment] 2022-01-21 08:50
I got the tokens sorted out earlier this month. We're hoping to deploy this action shortly: https://github.com/marketplace/actions/dockerhub-build-and-push

**Comment by ruffsl** [comment] 2022-02-16 20:32
Closing with https://github.com/osrf/docker_images/pull/588#issuecomment-1042236352

**Closed by ruffsl** 2022-02-16 20:33 UTC

**Comment by tfoote** [comment] 2022-03-03 20:09
Thanks for pushing this all through @ruffsl !
