### ISSUE TITLE
Foxy's image is outdated

### ISSUE THREAD

**Issue by quarkytale** [osrf/docker_images#671] opened 2023-04-24 22:33 UTC
`docker pull ros:foxy` returns a slightly outdated image. 

```
$ docker pull ros:foxy
foxy: Pulling from library/ros
Digest: sha256:a3a3f407b3fa69ad3bda20f822f913e3fe8d06a2616dbbcb5e8336a3ce026a51
Status: Image is up to date for ros:foxy
```
Inspecting it reveals that it is dated from about a week before this release:

```
docker inspect  ros:foxy | grep Created
        "Created": "2023-03-16T04:22:25.25731637Z",
```
And the packages inside are out of date:

```
ros-foxy-rclcpp/focal 2.4.2-1focal.20230317.010104 amd64 [upgradable from: 2.4.2-1focal.20221012.230743]                                                                                                   
ros-foxy-rclpy/focal 1.0.12-1focal.20230317.005942 amd64 [upgradable from: 1.0.11-1focal.20221012.230545]

```

What's the update cycle or the process to upload a new image?

Ref: https://discourse.ros.org/t/new-packages-and-patch-release-for-foxy-fitzroy-2023-03-22/30489/2

**Comment by sloretz** [comment] 2023-04-24 23:16
> What's the update cycle or the process to upload a new image?

There isn't a good way to update the images after a sync. Docker images in the [official library](https://github.com/docker-library/official-images/blob/master/library/ros) are cached in a way that we don't yet have the ability to invalidate. The `ros` images will get updated when the [base ubuntu image is updated](https://github.com/osrf/docker_images/blob/ef1bd96834a5a955183c24c1b220d2d58337e6ef/ros/foxy/ubuntu/focal/ros-core/Dockerfile#L3).

Duplicate of https://github.com/osrf/docker_images/issues/112

**Comment by mikaelarguedas** [comment] 2023-04-27 03:34
When did you run the previous commands ?

Looking at it, the image is up to date and was pushed [9 days ago](https://hub.docker.com/layers/library/ros/foxy/images/sha256-5991759125bfb3b5f7b99ea8d89519c620973f2fafe9f578b06683a187dd4b90?context=explore)

The ubuntu base images are updated roughly every ~3 weeks. So if the timing is unfortunate between a ROS sync and an ubuntu image update it can take about that time for the images to be updated.

**Comment by mikaelarguedas** [comment] 2023-06-27 14:24
closing as it was a ponctual issue and foxy's final image has now been built

**Closed by mikaelarguedas** 2023-06-27 14:24 UTC
