### ISSUE TITLE
ROS GPG Key Expiration Incident

### ISSUE THREAD

**Issue by okalachev** [osrf/docker_images#535] opened 2021-05-29 03:38 UTC
Running:

```bash
docker run --rm ros:melodic-ros-base /bin/bash
```

Running inside the container:

```bash
apt-get update
```

Getting:

```
...
Reading package lists... Done                                
W: GPG error: http://packages.ros.org/ros/ubuntu bionic InRelease: The following signatures were invalid: EXPKEYSIG F42ED6FBAB17C654 Open Robotics <info@osrfoundation.org>
E: The repository 'http://packages.ros.org/ros/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

It used to work earlier.

**Comment by ruffsl** [comment] 2021-05-29 05:13
I was able to reproduce this from a fresh image pull, but I'm not sure the issue lies here with the ros docker image, but perhaps with the missing signatures in the apt repo? cc @nuclearsandwich @tfoote

**Comment by LanderU** [comment] 2021-05-29 06:57
@ruffsl, there is an error with apt-keys see: https://discourse.ros.org/t/key-for-downloading-ros2-source-showing-expired/20662

**Comment by realtime-neil** [comment] 2021-05-29 18:13
Expired pubkey: https://github.com/ros/rosdistro/issues/29715

**Comment by realtime-neil** [comment] 2021-05-29 18:20
As of this writing, all of the following tags have the expired public key:

```
$ for ros_distro in kinetic melodic noetic dashing eloquent foxy galactic rolling; do docker image pull ros:${ros_distro} && docker container run -it --rm "ros:${ros_distro}" apt-key list 0xc1cf6e31e6bade8868b172b4f42ed6fbab17c654 ; done
kinetic: Pulling from library/ros
Digest: sha256:61431c9c6ab9e97b9d9883315cee10e30011a11cf10fa6e8dd4a22ebb701cc0b
Status: Image is up to date for ros:kinetic
docker.io/library/ros:kinetic
pub   4096R/AB17C654 2019-05-30 [expired: 2021-05-29]
uid                  Open Robotics <info@osrfoundation.org>

melodic: Pulling from library/ros
Digest: sha256:8bc813bfbc0be642aaf19ece731c938971200aa4624035b782b9265ffcefcec5
Status: Image is up to date for ros:melodic
docker.io/library/ros:melodic
pub   rsa4096 2019-05-30 [SC] [expired: 2021-05-29]
      C1CF 6E31 E6BA DE88 68B1  72B4 F42E D6FB AB17 C654
uid           [ expired] Open Robotics <info@osrfoundation.org>

noetic: Pulling from library/ros
Digest: sha256:852affb6da820b8b08a6016711e2c1bd841d8ea51d21654fb8815aa61a358bca
Status: Image is up to date for ros:noetic
docker.io/library/ros:noetic
pub   rsa4096 2019-05-30 [SC] [expired: 2021-05-29]
      C1CF 6E31 E6BA DE88 68B1  72B4 F42E D6FB AB17 C654
uid           [ expired] Open Robotics <info@osrfoundation.org>

dashing: Pulling from library/ros
Digest: sha256:6fded8bdabab827f94c806c50872143da2356aa9a472075f579495b2ce5e435d
Status: Image is up to date for ros:dashing
docker.io/library/ros:dashing
pub   rsa4096 2019-05-30 [SC] [expired: 2021-05-29]
      C1CF 6E31 E6BA DE88 68B1  72B4 F42E D6FB AB17 C654
uid           [ expired] Open Robotics <info@osrfoundation.org>

eloquent: Pulling from library/ros
Digest: sha256:84b84546b9a531f5a6b8decf2f3abab40f5b3648a5d6bf7c07c580c01304ccee
Status: Image is up to date for ros:eloquent
docker.io/library/ros:eloquent
pub   rsa4096 2019-05-30 [SC] [expired: 2021-05-29]
      C1CF 6E31 E6BA DE88 68B1  72B4 F42E D6FB AB17 C654
uid           [ expired] Open Robotics <info@osrfoundation.org>

foxy: Pulling from library/ros
Digest: sha256:9500ecb21f52d1df7aa1522004456b4d7a7655ad259230f94306f096ed62dca3
Status: Image is up to date for ros:foxy
docker.io/library/ros:foxy
pub   rsa4096 2019-05-30 [SC] [expired: 2021-05-29]
      C1CF 6E31 E6BA DE88 68B1  72B4 F42E D6FB AB17 C654
uid           [ expired] Open Robotics <info@osrfoundation.org>

galactic: Pulling from library/ros
Digest: sha256:a432f1df997d95643a180f304279901d3bac630a0fbee12b5406f918d69dad5f
Status: Image is up to date for ros:galactic
docker.io/library/ros:galactic
pub   rsa4096 2019-05-30 [SC] [expired: 2021-05-29]
      C1CF 6E31 E6BA DE88 68B1  72B4 F42E D6FB AB17 C654
uid           [ expired] Open Robotics <info@osrfoundation.org>

rolling: Pulling from library/ros
Digest: sha256:3b9dd1f290462f8ddd7c596bed7f7b967a152b81fffa0d5e97f521a7b6581ca3
Status: Image is up to date for ros:rolling
docker.io/library/ros:rolling
pub   rsa4096 2019-05-30 [SC] [expired: 2021-05-29]
      C1CF 6E31 E6BA DE88 68B1  72B4 F42E D6FB AB17 C654
uid           [ expired] Open Robotics <info@osrfoundation.org>

```

**Comment by realtime-neil** [comment] 2021-05-29 18:33
This can be fixed with a maintainer-triggered rebuild of all images.

I've already [published the new key to keyserver](https://github.com/ros/rosdistro/issues/29715#issuecomment-850854493) and  this repo already has the necessary invocations to grab it:

```
$ echo && git remote --verbose && echo && git grep C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

origin	https://github.com/osrf/docker_images.git (fetch)
origin	https://github.com/osrf/docker_images.git (push)

ros/ardent/ubuntu/xenial/ros1-bridge/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/bouncy/ubuntu/bionic/ros1-bridge/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/crystal/ubuntu/bionic/ros1-bridge/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/dashing/ubuntu/bionic/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/dashing/ubuntu/bionic/ros1-bridge/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/eloquent/ubuntu/bionic/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/eloquent/ubuntu/bionic/ros1-bridge/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/foxy/ubuntu/focal/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/foxy/ubuntu/focal/ros1-bridge/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/galactic/ubuntu/focal/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/galactic/ubuntu/focal/ros1-bridge/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/kinetic/ubuntu/xenial/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/melodic/debian/stretch/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/melodic/ubuntu/bionic/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/noetic/debian/buster/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/noetic/ubuntu/focal/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/rolling/ubuntu/focal/ros-core/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros/rolling/ubuntu/focal/ros1-bridge/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros2/nightly/nightly/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
ros2/source/devel/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sros/kinetic/Dockerfile:RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

```

So, can we get a maintainer to do a "manual" trigger on all tags, please?

**Comment by ruffsl** [comment] 2021-05-29 18:53
> So, can we get a maintainer to do a "manual" trigger on all tags, please?

Given how ros org updated the key, with the same fingerprint fire the keysever, there's currently no changes to the Dockerfiles that would subsequently break the build cache for the official Docker hub library. Thus the official library images would remain unchanged until the Ubuntu or Debian parent images update.

Suggestions for templates charges to the core tags would be welcome in order to break the build cash upstream.

**Comment by realtime-neil** [comment] 2021-05-29 19:04
> > So, can we get a maintainer to do a "manual" trigger on all tags, please?
> 
> Given how ros org updated the key, with the same fingerprint fire the keysever, there's currently no changes to the Dockerfiles that would subsequently break the build cache for the official Docker hub library. Thus the official library images would remain unchanged until the Ubuntu or Debian parent images update.

Noted. Let's call this a cautionary tale against republishing an "updated" key under the same identifier.

**Comment by mikaelarguedas** [comment] 2021-05-29 19:17
Good news is that as this happened only on packages.ros.org but not on snapshots.ros.org, all the EOL and regacy images are not impacted.

For the images using packages.ros.org, we can check:
1 - if the ones that are EOL finally have a final snapshots, in that case the best thing would be to transition them over to the snapshots apt repo that way it's win-win
2 for the images  that are not EOL or are EOL but dont have a final snapshots,
2a - Ask the official docker librarian if they have a way to trigger rebuild without cache
2b - Make a change early in the dockerfiles to force a cache break and actually get the new key. Unlikely the librarians would allow unuseful changes. So maybe its the opportunity to insert a way to put something that will force the images to stay up-to--date in the future (ala https://github.com/osrf/docker_images/pull/457 but with another approach as the librarian rejected that one). 
2c. A change without functional impact that doesnt introduce dummy layers and adds no new functionality. Maybe we can just swap creating the source.list file and adding the key ?
```diff
-# setup keys
-RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
-
 # setup sources.list
 RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros1-latest.list
 
+# setup keys
+RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
+
```

This will force a rebuild and not change anything ?

**Comment by ruffsl** [comment] 2021-05-29 20:08
> 1 - if the ones that are EOL finally have a final snapshots, in that case the best thing would be to transition them over to the snapshots apt repo that way it's win-win

:+1: 

> 2a - Ask the official docker librarian if they have a way to trigger rebuild without cache

I don't think the librarians can, at least from what I recall when I asked them about this on IRC. I think the jenkins CI for building all the images defaults to using the build cache from existing layers in the registry, thus why many of the unmodified tags in CI jobs are so speedy:

https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/ros/

> 2b - Make a change early in the dockerfiles to force a cache break and actually get the new key. Unlikely the librarians would allow unuseful changes. So maybe its the opportunity to insert a way to put something that will force the images to stay up-to--date in the future (ala #457 but with another approach as the librarian rejected that one).

We could push for using `ARG` instead of using `LABEL` to embed the cache breaks for package updates, given it doesn't suffer like the later; as it avoids embedding unused metadata in the image.

https://github.com/docker-library/official-images/pull/8786#issuecomment-729165987

> 2c. A change without functional impact that doesnt introduce dummy layers and adds no new functionality. Maybe we can just swap creating the source.list file and adding the key ?

Perhaps we could just update to incorporate instruction changes for the apt repo installation:

https://github.com/ros2/ros2_documentation/pull/1189
https://github.com/ros2/ros2_documentation/pull/1189#discussion_r605169268

E.g:

``` diff
- RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros2-latest.list
+ RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros2.list
```

**Comment by mikaelarguedas** [comment] 2021-05-29 20:15
> 1 - if the ones that are EOL finally have a final snapshots, in that case the best thing would be to transition them over to the snapshots apt repo that way it's win-win

Integrating those now looks like a few snapshots appeared since last time

> We could push for using ARG instead of using LABEL to embed the cache breaks for package updates, given it doesn't suffer like the later; as it avoids embedding unused metadata in the image.

We held off as they never replied to that comment. Let's keep that one for later as it will make it more likely to have to iterate with them and may delay the fixing of the images

> Perhaps we could just update to incorporate instruction changes for the apt repo installation:

> ros2/ros2_documentation#1189
> ros2/ros2_documentation#1189 (comment)

> E.g:
```diff
- RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros2-latest.list
+ RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros2.list
```

Not a big fan of this one. We use the suffix to also discriminat between `ros2-snapshots.list` and `ros2-latest.list` (and the current template generation does expect a suffix so we'd need to change more things to do just `ros2.list`

**Comment by ruffsl** [comment] 2021-05-29 20:22
> Not a big fan of this one.

Hmm, but what about the other changes from the PR for future proofing use of third-party repositories?

https://wiki.debian.org/DebianRepository/UseThirdParty#Sources.list_entry

**Comment by cottsay** [comment] 2021-05-29 20:23
I'm not sure I understand why the keyserver is being used at all here. The latest instructions involve downloading the key over HTTPS via a known URL.

This seems like a great opportunity to use the docker [`ADD` command](https://docs.docker.com/engine/reference/builder/#add). Pull the file to the location mentioned in the instructions, and if the checksum ever changes, break the cache. Each build will re-download the 1.1k file for evaluation, which seems a small price to pay.

**Comment by ruffsl** [comment] 2021-05-29 20:32
> I'm not sure I understand why the keyserver is being used at all here. The latest instructions involve downloading the key over HTTPS via a known URL.

We initially used a keyserver, as it's prescribed by the security conventions for the official library: 

https://github.com/docker-library/official-images#image-build

> This seems like a great opportunity to use the docker [`ADD` command](https://docs.docker.com/engine/reference/builder/#add). Pull the file to the location mentioned in the instructions, and if the checksum ever changes, break the cache. Each build will re-download the 1.1k file for evaluation, which seems a small price to pay.

Clever. You could try and deviate on this, but then we'd have to convince the librarians. I'm thinking they'd argue pinning the key by it's fingerprint is more secure than just pinning the URL it's fetched from.

**Comment by mikaelarguedas** [comment] 2021-05-30 10:50
> Clever. You could try and deviate on this, but then we'd have to convince the librarians. I'm thinking they'd argue pinning the key by it's fingerprint is more secure than just pinning the URL it's fetched from.

I'll go with simply swapping the 2 RUN commands and ask them in the PR if they'd accept such a change in the future.
https://github.com/osrf/docker_images/pull/538 https://github.com/osrf/docker_images/pull/536

> Integrating those now looks like a few snapshots appeared since last time

Eloquent and Melodic/Stretch will now use snapshots https://github.com/osrf/docker_images/pull/537

---

The main issue we'll have is to fix the ros1-bridge images for eol ros2 distros
If we rebuild the images they will try to install the pinned versions of ros-comm and other ROS1 packages, but they won't be available. If wi update to the current version of these packages:
- we dont provide the same images as before just to fix a key issue
- the new version of ros-comm and friends broke things in dependencies so the images failed to build:

<details><summary>Error messages crystal</summary>

```
Step 6/10 : RUN apt-get update && apt-get install -y     ros-melodic-ros-comm=1.14.11-1*     ros-melodic-roscpp-tutorials=0.9.3-1*     ros-melodic-rospy-tutorials=0.9.3-1*     && rm -rf /var/lib/apt/lists/*

The following packages have unmet dependencies:
 ros-melodic-ros-comm : Depends: ros-melodic-ros but it is not going to be installed
                        Depends: ros-melodic-rosbag but it is not going to be installed
                        Depends: ros-melodic-roslaunch but it is not going to be installed
                        Depends: ros-melodic-roslisp but it is not going to be installed
                        Depends: ros-melodic-rosmsg but it is not going to be installed
                        Depends: ros-melodic-rosnode but it is not going to be installed
                        Depends: ros-melodic-rospy but it is not going to be installed
                        Depends: ros-melodic-rosservice but it is not going to be installed
                        Depends: ros-melodic-rostest but it is not going to be installed
                        Depends: ros-melodic-rostopic but it is not going to be installed
                        Depends: ros-melodic-roswtf but it is not going to be installed
 ros-melodic-rospy-tutorials : Depends: ros-melodic-rospy but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update && apt-get install -y     ros-melodic-ros-comm=1.14.11-1*     ros-melodic-roscpp-tutorials=0.9.3-1*     ros-melodic-rospy-tutorials=0.9.3-1*     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
make: *** [Makefile:16: build] Error 100

```

</details>

<details><summary>Error message bouncy</summary>

```
The following packages have unmet dependencies:
 ros-melodic-ros-comm : Depends: ros-melodic-ros but it is not going to be installed
                        Depends: ros-melodic-rosbag but it is not going to be installed
                        Depends: ros-melodic-roslaunch but it is not going to be installed
                        Depends: ros-melodic-roslisp but it is not going to be installed
                        Depends: ros-melodic-rosmsg but it is not going to be installed
                        Depends: ros-melodic-rosnode but it is not going to be installed
                        Depends: ros-melodic-rospy but it is not going to be installed
                        Depends: ros-melodic-rosservice but it is not going to be installed
                        Depends: ros-melodic-rostest but it is not going to be installed
                        Depends: ros-melodic-rostopic but it is not going to be installed
                        Depends: ros-melodic-roswtf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update && apt-get install -y     ros-melodic-ros-comm=1.14.11-1*     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
make: *** [Makefile:16: build] Error 100

```

</details>

**Comment by John2397** [comment] 2021-05-31 12:12
I'm also facing the same problem on ROS1, using the ros:noetic image.

Is there any workaround for this until the issue is fixed?

Thank you.

**Comment by rickstaa** [comment] 2021-05-31 13:51
@John2397 As explained by @mikaelarguedas in this [comment](https://github.com/osrf/docker_images/issues/535#issuecomment-850892680), adding the updated key at the top of the docker file that is based on the `ros:noetic image.` image fixes the issue.

```bash
# Fix ros key
# NOTE: Needed because of this bug https://github.com/osrf/docker_images/issues/535
apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
`

**Comment by mikaelarguedas** [comment] 2021-06-02 18:46
> This seems like a great opportunity to use the docker ADD command. Pull the file to the location mentioned in the instructions, and if the checksum ever changes, break the cache. Each build will re-download the 1.1k file for evaluation, which seems a small price to pay.

As suspected this is not an approach the librarian are found of: https://github.com/docker-library/official-images/pull/10272#issuecomment-853248556, they recommend using our current approach: [Official recommendations](https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification)

**Comment by richmattes** [comment] 2021-06-02 21:14
It doesn't look like the docker-library PR included an update for `noetic-ros-core` or `foxy-ros-core`.

**Comment by mikaelarguedas** [comment] 2021-06-02 21:20
Yes thanks for reporting it. I have a branch ready with those changes and will submit a PR upstream shortly along the retiring of the EOL images

**Comment by brennand** [comment] 2021-06-03 19:33
Do you know when the new keys will propagate to the main docker images?

**Comment by mikaelarguedas** [comment] 2021-06-03 20:07
All the images in the main docker library (the ones starting with `ros:` like `ros:noetic-ros-base`) should now be available with the new key.
The ones in in the osrf profile (e.g. `osrf/ros:noetic-desktop`) are in the build queue but not rebuilt yet

**Comment by rickstaa** [comment] 2021-06-03 20:50
@brennand @mikaelarguedas Looks like they just finished (see https://hub.docker.com/r/osrf/ros/builds/?page=1).

**Comment by mikaelarguedas** [comment] 2021-06-03 21:00
That page shows only the finished jobs when not signed in.
the following ones are still in the queue:
```
kinetic-desktop-full-xenial
melodic-desktop-full-bionic
melodic-desktop-full-stretch
noetic-desktop-buster
noetic-desktop-focal
noetic-desktop-full-buster
noetic-desktop-full-focal
rolling-desktop
```

**Comment by rickstaa** [comment] 2021-06-03 21:06
@mikaelarguedas Ah I missed that, thanks for the explanation!

**Comment by mikaelarguedas** [comment] 2021-06-04 05:22
The new key has now propagated to all `ros:*` and `osrf/ros:*` images, closing this incident ticket. Thanks all for your patience.

If you encounter any issues don't hesitate to comment here and we'll reopen.

**Closed by mikaelarguedas** 2021-06-04 05:22 UTC
