### ISSUE TITLE
GPG error in ros1_bridge containers

### ISSUE THREAD

**Issue by ErikAtApex** [osrf/docker_images#579] opened 2021-12-07 20:38 UTC
Steps to reproduce:

```
#Dockerfile.ros1_bridge
FROM osrf/ros:foxy-ros1-bridge
RUN apt-get update
```

```
> docker build . -f Dockerfile.ros1_bridge --pull --no-cache
W: GPG error: http://packages.ros.org/ros2/ubuntu focal InRelease: The following signatures were invalid: EXPKEYSIG F42ED6FBAB17C654 Open Robotics <info@osrfoundation.org>
E: The repository 'http://packages.ros.org/ros2/ubuntu focal InRelease' is not signed.
```

Expected behavior:

`apt-get update` completes successfully

In addition, the recommended workaround of using `curl` to update the key manually won't work, because `curl` is not installed, and you can't use `apt-get` to install it :smile:

Thank you folks!

**Comment by mikaelarguedas** [comment] 2022-02-09 08:51
@ErikAtApex thanks for reporting. This seems like some key servers still didnt get the update GPG keys from many months ago.
From Europe I've been unable to reproduce the issue. Is there anything special in your setup (like enterprise network redirect making you hit a specific key server) ?

**Comment by ErikAtApex** [comment] 2022-02-09 17:19
Hi @mikaelarguedas ! Thanks for looking into this. I'm on my home network, but I have also reproduced this on the free GitLab CI runners. Several coworkers are able to reproduce as well, both in USA and Europe:

```
mkdir -p erik_test
cd erik_test
printf 'FROM osrf/ros:foxy-ros1-bridge\nRUN apt-get update' > Dockerfile.ros1_bridge
docker build . -f Dockerfile.ros1_bridge --pull --no-cache
```
yields the following output:
```
W: GPG error: http://packages.ros.org/ros/ubuntu focal InRelease: The following signatures were invalid: EXPKEYSIG F42ED6FBAB17C654 Open Robotics <info@osrfoundation.org>
E: The repository 'http://packages.ros.org/ros/ubuntu focal InRelease' is not signed.
W: GPG error: http://packages.ros.org/ros2/ubuntu focal InRelease: The following signatures were invalid: EXPKEYSIG F42ED6FBAB17C654 Open Robotics <info@osrfoundation.org>
E: The repository 'http://packages.ros.org/ros2/ubuntu focal InRelease' is not signed.
```

**Comment by mikaelarguedas** [comment] 2022-02-09 17:33
oh interesting, the ros1-bridge images are now part of the official docker library, I thought the old ones were retired.
Can you test if you have the issue by pulling `ros:foxy-ros1-bridge` instead of `osrf/ros:foxy-ros1-bridge` ?

**Comment by ErikAtApex** [comment] 2022-02-09 17:41
@mikaelarguedas yes, you found it! It works with `ros:foxy-ros1-bridge`. Thank you :pray:

**Comment by mikaelarguedas** [comment] 2022-02-09 17:44
Good to hear, I'll see if we can delete the old ones definitively.
Do you happen to know if you followed any tutorial or doc pointing to that image ?

**Comment by ErikAtApex** [comment] 2022-02-09 18:26
@mikaelarguedas It was referenced in an old issue of the ros2 repository, so I wanted to try it out :smile:  Here is the comment: https://github.com/ros2/ros2/issues/950#issuecomment-645758139

**Comment by mikaelarguedas** [comment] 2022-02-09 18:29
ok great, if people fix the same issue they will be able to find the solution thanks to this issue and the cross-referencing :+1:

I'll close this one then

**Closed by mikaelarguedas** 2022-02-09 18:29 UTC

**Comment by ErikAtApex** [comment] 2022-02-09 18:35
@mikaelarguedas thanks again! Is there any situation where you would prefer to use the `osrf/ros:<image>` over the equivalent `ros:<image>`?

**Comment by mikaelarguedas** [comment] 2022-02-10 04:26
In general we recommend using the official ones (the ones without the `osrf` in front).
There are some restrictions in what can be included in the official images, for example gui dependencies and tools are discouraged, this is why the more "complete" images are hosted on the `osrf` docker profile.

From this repo's readme:

[Official Library](https://docs.docker.com/docker-hub/official_images)

The following repos are hosted under the Official Library on Docker Hub. These images are tagged for production and general downstream use. If you’re targeting released versions of respective projects, then these are recommended.

[OSRF Profile](https://hub.docker.com/u/osrf/)

The following repos are hosted under the OSRF Organization on Docker Hub. These images are tagged for development and advanced use cases. If you require extra dependencies not available from the Official Library images above, then using these images may help save you build time during continuous integration or local development.
